import type {
  Tournament,
  Match,
  User,
  MatchResult,
  TournamentEntry,
  Payout,
  QuickMatch,
  LeaderboardEntry
} from '@/app/types';

// ============================================
// Mock Users
// ============================================
export const mockUsers: User[] = [
  {
    id: 'user_001',
    email: 'rahul@example.com',
    phone: '9876543210',
    name: 'Rahul Sharma',
    displayName: 'RahulGamer',
    avatarUrl: '/images/avatars/user-1.jpg',
    bannerUrl: '/images/banners/user-1-banner.jpg',
    bgmiId: '5123456789',
    pubgId: null,
    role: 'PARTICIPANT',
    isEmailVerified: true,
    isPhoneVerified: true,
    dateOfBirth: '2000-05-15',
    ageVerifiedAt: '2024-01-15T10:30:00Z',
    kycStatus: 'APPROVED',
    state: 'Maharashtra',
    stats: {
      tournamentsPlayed: 24,
      tournamentsWon: 3,
      totalEarnings: 1250000,
      totalKills: 156,
      winRate: 12.5,
      avgPlacement: 8.4,
      matchesPlayed: 145,
    },
    gamingProfile: {
      fullName: 'Rahul Sharma',
      mobileNumber: '9876543210',
      isMobileVerified: true,
      country: 'India',
      state: 'Maharashtra',
      preferredGame: 'BGMI',
      bgmiId: '5123456789',
      bgmiUsername: 'RahulGamer',
      pubgId: '',
      pubgUsername: '',
      preferredMatchTypes: ['CLASSIC', 'TDM'],
      device: 'ANDROID',
      clanName: 'Alpha Squad',
      discordId: 'rahul#1234',
      profileCompleteness: 100,
      isProfileLocked: true,
      onboardingCompleted: true,
    },
    joinedTournamentIds: ['trn_001', 'trn_002'],
    wallet: {
      cash: 245000,
      pendingWithdrawal: 0,
    },
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 'user_002',
    email: 'priya@example.com',
    phone: '9876543211',
    name: 'Priya Patel',
    displayName: 'PriyaPlays',
    avatarUrl: '/images/avatars/user-2.jpg',
    bannerUrl: null,
    bgmiId: '5123456790',
    pubgId: null,
    role: 'PARTICIPANT',
    isEmailVerified: true,
    isPhoneVerified: true,
    dateOfBirth: '1999-08-20',
    ageVerifiedAt: '2024-02-10T14:00:00Z',
    kycStatus: 'APPROVED',
    state: 'Gujarat',
    stats: {
      tournamentsPlayed: 18,
      tournamentsWon: 2,
      totalEarnings: 850000,
      totalKills: 98,
      winRate: 11.1,
      avgPlacement: 12.2,
      matchesPlayed: 86,
    },
    gamingProfile: {
      fullName: 'Priya Patel',
      mobileNumber: '9876543211',
      isMobileVerified: true,
      country: 'India',
      state: 'Gujarat',
      preferredGame: 'BOTH',
      bgmiId: '5123456790',
      bgmiUsername: 'PriyaPlays',
      pubgId: '6123456789',
      pubgUsername: 'PriyaPUBG',
      preferredMatchTypes: ['ARENA', 'CLASSIC'],
      device: 'IOS',
      profileCompleteness: 100,
      isProfileLocked: true,
      onboardingCompleted: true,
    },
    wallet: {
      cash: 85000,
      pendingWithdrawal: 0,
    },
    createdAt: '2024-02-10T14:00:00Z',
  },
  {
    id: 'org_001',
    email: 'progaming@example.com',
    phone: '9876543212',
    name: 'ProGaming India',
    displayName: 'ProGaming India',
    avatarUrl: '/images/avatars/org-1.jpg',
    bgmiId: null,
    pubgId: null,
    role: 'ORGANIZER',
    isEmailVerified: true,
    isPhoneVerified: true,
    dateOfBirth: '1995-01-01',
    ageVerifiedAt: '2024-01-01T00:00:00Z',
    kycStatus: 'APPROVED',
    state: 'Karnataka',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'admin_001',
    email: 'admin@example.com',
    phone: '9876543213',
    name: 'Admin User',
    displayName: 'Admin',
    avatarUrl: '/images/avatars/admin-1.jpg',
    bgmiId: null,
    pubgId: null,
    role: 'ADMIN',
    isEmailVerified: true,
    isPhoneVerified: true,
    dateOfBirth: '1990-01-01',
    ageVerifiedAt: '2024-01-01T00:00:00Z',
    kycStatus: 'APPROVED',
    state: 'Delhi',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user_new',
    email: 'newplayer@example.com',
    phone: '',
    name: 'New Player',
    displayName: 'NewPlayer',
    avatarUrl: null,
    bgmiId: null,
    pubgId: null,
    role: 'PARTICIPANT',
    isEmailVerified: true,
    isPhoneVerified: false,
    dateOfBirth: '',
    ageVerifiedAt: null,
    kycStatus: 'NOT_SUBMITTED',
    state: '',
    gamingProfile: {
      fullName: '',
      mobileNumber: '',
      isMobileVerified: false,
      country: 'India',
      state: '',
      preferredGame: 'BGMI',
      bgmiId: '',
      bgmiUsername: '',
      pubgId: '',
      pubgUsername: '',
      preferredMatchTypes: [],
      device: '',
      profileCompleteness: 0,
      isProfileLocked: false,
      onboardingCompleted: false,
    },
    wallet: {
      cash: 0,
      pendingWithdrawal: 0,
    },
    createdAt: new Date().toISOString(),
  },
];

// ============================================
// Mock Quick Matches
// ============================================
export const mockQuickMatches: QuickMatch[] = [
  {
    id: '1',
    title: 'Erangel Squad Match',
    mode: 'CLASSIC',
    game: 'BGMI',
    map: 'ERANGEL',
    perspective: 'TPP',
    entryFee: 50,
    prizePerKill: 10,
    maxPlayers: 100,
    currentPlayers: 45,
    startsAt: new Date(Date.now() + 1000 * 60 * 15).toISOString(), // 15 mins from now
    status: 'FILLING',
  },
  {
    id: '2',
    title: 'Warehouse TDM Match',
    mode: 'ARENA',
    game: 'BGMI',
    map: 'TDM',
    perspective: 'FPP',
    entryFee: 20,
    prizePerKill: 5,
    maxPlayers: 8,
    currentPlayers: 8,
    startsAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // Started 5 mins ago
    status: 'LIVE',
  },
  {
    id: '3',
    title: 'Livik Fast Match',
    mode: 'CLASSIC',
    game: 'BGMI',
    map: 'LIVIK',
    perspective: 'TPP',
    entryFee: 30,
    prizePerKill: 8,
    maxPlayers: 50,
    currentPlayers: 12,
    startsAt: new Date(Date.now() + 1000 * 60 * 30).toISOString(),
    status: 'FILLING',
  },
  {
    id: '4',
    title: 'Sniper Training Dust2',
    mode: 'ARCADE',
    game: 'PUBG_MOBILE',
    map: 'SNIPER_TRAINING',
    perspective: 'FPP',
    entryFee: 40,
    prizePerKill: 15,
    maxPlayers: 20,
    currentPlayers: 18,
    startsAt: new Date(Date.now() + 1000 * 60 * 60).toISOString(),
    status: 'FILLING',
  },
  {
    id: '5',
    title: 'Sanhok Close Encounters',
    mode: 'CLASSIC',
    game: 'BGMI',
    map: 'SANHOK',
    perspective: 'TPP',
    entryFee: 60,
    prizePerKill: 12,
    maxPlayers: 100,
    currentPlayers: 82,
    startsAt: new Date(Date.now() + 1000 * 60 * 45).toISOString(),
    status: 'FILLING',
  },
  {
    id: '6',
    title: 'Miramar Long Shots',
    mode: 'CLASSIC',
    game: 'BGMI',
    map: 'MIRAMAR',
    perspective: 'TPP',
    entryFee: 100,
    prizePerKill: 25,
    maxPlayers: 100,
    currentPlayers: 21,
    startsAt: new Date(Date.now() + 1000 * 60 * 120).toISOString(),
    status: 'FILLING',
  },
];

// ============================================
// Mock Leaderboard
// ============================================
export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: 'user_003',
    displayName: 'ProKiller',
    avatarUrl: '/images/avatars/user-3.jpg',
    totalKills: 1250,
    totalWins: 89,
    winRate: 35.6,
    totalEarnings: 12500000,
    tier: 'CONQUEROR',
  },
  {
    rank: 2,
    userId: 'user_004',
    displayName: 'BGMIMaster',
    avatarUrl: '/images/avatars/user-4.jpg',
    totalKills: 1120,
    totalWins: 76,
    winRate: 32.4,
    totalEarnings: 11200000,
    tier: 'ACE',
  },
  {
    rank: 3,
    userId: 'user_005',
    displayName: 'SnipeKing',
    avatarUrl: '/images/avatars/user-5.jpg',
    totalKills: 980,
    totalWins: 98,
    winRate: 38.2,
    totalEarnings: 10800000,
    tier: 'ACE',
  },
  {
    rank: 4,
    userId: 'user_001',
    displayName: 'RahulGamer',
    avatarUrl: '/images/avatars/user-1.jpg',
    totalKills: 156,
    totalWins: 23,
    winRate: 15.8,
    totalEarnings: 8500000,
    tier: 'DIAMOND',
  },
];

// ============================================
// Mock Tournaments
// ============================================
export const mockTournaments: Tournament[] = [
  {
    id: 'trn_001',
    title: 'Weekend Big Prize Match',
    slug: 'weekend-big-prize-match',
    game: 'BGMI',
    format: 'SQUAD',
    description: 'Play in the biggest squad match of the week!',
    rules: 'Rules text here',
    organizerId: 'org_001',
    organizerName: 'ProGaming India',
    organizerVerified: true,
    registrationStartsAt: '2026-01-05T10:00:00Z',
    registrationEndsAt: '2026-01-10T18:00:00Z',
    startsAt: '2026-01-11T19:00:00Z',
    endsAt: null,
    maxParticipants: 100,
    minParticipants: 20,
    currentParticipants: 76,
    entryFee: 5000,
    prizePool: 5000000,
    prizeDistribution: [
      { position: 1, amount: 2500000, label: '1st Place' },
    ],
    prizePerKill: 1000,
    firstPrice: 2500000,
    secondPrice: 1500000,
    thirdPrice: 1000000,
    status: 'REGISTRATION_OPEN',
    approvedAt: '2026-01-04T12:00:00Z',
    approvedBy: 'admin_001',
    thumbnailUrl: '/games/bgmi_classic.png',
    modeCategory: 'CLASSIC',
    map: 'ERANGEL',
    perspective: 'TPP',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trn_002',
    title: 'Solo Hero Series',
    slug: 'solo-hero-series',
    game: 'BGMI',
    format: 'SOLO',
    description: 'Prove you are the best solo player!',
    rules: 'Rules text here',
    organizerId: 'org_001',
    organizerName: 'ProGaming India',
    organizerVerified: true,
    registrationStartsAt: '2026-01-06T10:00:00Z',
    registrationEndsAt: '2026-01-12T18:00:00Z',
    startsAt: '2026-01-13T20:00:00Z',
    endsAt: null,
    maxParticipants: 100,
    minParticipants: 50,
    currentParticipants: 45,
    entryFee: 2500,
    prizePool: 2500000,
    prizeDistribution: [
      { position: 1, amount: 1250000, label: '1st Place' },
    ],
    prizePerKill: 500,
    firstPrice: 1250000,
    secondPrice: 750000,
    thirdPrice: 500000,
    status: 'REGISTRATION_OPEN',
    approvedAt: '2026-01-05T10:00:00Z',
    approvedBy: 'admin_001',
    thumbnailUrl: '/games/bgmi_solo.png',
    modeCategory: 'ARENA',
    map: 'MIRAMAR',
    perspective: 'TPP',
    createdAt: new Date().toISOString(),
    updatedAt: '2026-01-05T10:00:00Z',
  },
];

// ============================================
// Mock Matches
// ============================================
export const mockMatches: Match[] = [
  {
    id: 'match_001',
    tournamentId: 'trn_003',
    tournamentTitle: 'Duo Domination Cup',
    matchNumber: 1,
    scheduledAt: '2026-01-03T21:00:00Z',
    roomCodeRevealAt: '2026-01-03T20:50:00Z',
    startedAt: '2026-01-03T21:05:00Z',
    endedAt: '2026-01-03T21:35:00Z',
    roomCode: 'BGMI1234',
    roomPassword: 'ARENA2026',
    status: 'COMPLETED',
    map: 'SANHOK',
    mode: 'Classic',
    resultsSubmitted: true,
    resultsApproved: true,
  },
];

// ============================================
// Mock Match Results
// ============================================
export const mockResults: MatchResult[] = [
  {
    id: 'result_001',
    matchId: 'match_001',
    rank: 1,
    userId: 'user_001',
    userName: 'RahulGamer',
    teamName: 'Team Alpha',
    placement: 1,
    kills: 12,
    placementPoints: 15,
    killPoints: 12,
    totalPoints: 27,
    prizeAmount: 750000,
    submittedBy: 'org_001',
    submittedAt: '2026-01-03T22:00:00Z',
    evidenceUrls: ['/evidence/match001_1.jpg'],
    status: 'APPROVED',
    reviewedBy: 'admin_001',
    reviewedAt: '2026-01-03T23:00:00Z',
    reviewNotes: 'Verified',
  },
];

// ============================================
// Mock Tournament Entries
// ============================================
export const mockEntries: TournamentEntry[] = [
  {
    id: 'entry_001',
    tournamentId: 'trn_001',
    userId: 'user_001',
    teamId: 'team_001',
    teamName: 'Team Alpha',
    teamMembers: [
      { userId: 'user_001', name: 'RahulGamer', role: 'LEADER' },
    ],
    slotNumber: 1,
    paymentId: 'pay_001',
    paymentStatus: 'COMPLETED',
    amountPaid: 5000,
    status: 'REGISTERED',
    registeredAt: '2026-01-06T14:30:00Z',
  },
];

// ============================================
// Mock Payouts
// ============================================
export const mockPayouts: Payout[] = [
  {
    id: 'payout_001',
    tournamentId: 'trn_003',
    tournamentTitle: 'Duo Domination Cup',
    userId: 'user_001',
    userName: 'RahulGamer',
    amount: 750000,
    status: 'PENDING',
    approvedBy: null,
    approvedAt: null,
    processedAt: null,
    razorpayId: null,
  },
];

// ============================================
// Current User (for mock auth)
// ============================================
export const mockCurrentUser = mockUsers[0];
